# Generated by Django 5.2.7 on 2025-11-26 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='draft', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Organigrama')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('chart_data', models.JSONField(default=dict, verbose_name='Datos del Organigrama')),
                ('is_main', models.BooleanField(default=False, verbose_name='Organigrama Principal')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Organigrama',
                'verbose_name_plural': 'Organigramas',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Puesto')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('level', models.CharField(max_length=50, verbose_name='Nivel Jerárquico')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizational.position', verbose_name='Reporta a')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='ProcessFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='draft', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proceso')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('flow_data', models.JSONField(default=dict, verbose_name='Datos del Flujo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('related_positions', models.ManyToManyField(blank=True, to='organizational.position', verbose_name='Puestos Relacionados')),
            ],
            options={
                'verbose_name': 'Flujograma',
                'verbose_name_plural': 'Flujogramas',
            },
        ),
    ]
