# Generated by Django 5.2.7 on 2025-11-26 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Comité')),
                ('type', models.CharField(choices=[('quality', 'Comité de Calidad'), ('safety', 'Comité de Seguridad e Higiene'), ('ethics', 'Comité de Ética'), ('emergency', 'Brigada de Protección Civil'), ('improvement', 'Comité de Mejora Continua'), ('other', 'Otro')], max_length=50, verbose_name='Tipo de Comité')),
                ('purpose', models.TextField(verbose_name='Propósito')),
                ('responsibilities', models.JSONField(default=list, verbose_name='Responsabilidades')),
                ('meeting_frequency', models.CharField(max_length=100, verbose_name='Frecuencia de Reuniones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Comité/Grupo',
                'verbose_name_plural': 'Comités/Grupos',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Habilidad')),
                ('category', models.CharField(choices=[('technical', 'Técnica'), ('safety', 'Seguridad'), ('quality', 'Calidad'), ('language', 'Idioma'), ('certification', 'Certificación'), ('software', 'Software')], default='technical', max_length=50, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_certification', models.BooleanField(default=False, verbose_name='Requiere Certificación')),
            ],
            options={
                'verbose_name': 'Habilidad/Competencia',
                'verbose_name_plural': 'Habilidades/Competencias',
            },
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Puesto (Caja)', 'verbose_name_plural': 'Puestos (Cajas)'},
        ),
        migrations.RemoveField(
            model_name='organizationalchart',
            name='chart_data',
        ),
        migrations.AddField(
            model_name='position',
            name='kpis',
            field=models.JSONField(default=list, verbose_name='KPIs del Puesto'),
        ),
        migrations.AddField(
            model_name='position',
            name='required_processes',
            field=models.JSONField(default=list, verbose_name='Procesos Requeridos'),
        ),
        migrations.AddField(
            model_name='position',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='Responsabilidades'),
        ),
        migrations.AddField(
            model_name='position',
            name='x_position',
            field=models.IntegerField(default=0, verbose_name='Posición X'),
        ),
        migrations.AddField(
            model_name='position',
            name='y_position',
            field=models.IntegerField(default=0, verbose_name='Posición Y'),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Nivel Jerárquico'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='ID Empleado')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('photo', models.ImageField(blank=True, upload_to='employees/', verbose_name='Foto')),
                ('hire_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado (Persona)',
                'verbose_name_plural': 'Empleados (Personas)',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('role', models.CharField(choices=[('president', 'Presidente'), ('secretary', 'Secretario'), ('member', 'Miembro'), ('coordinator', 'Coordinador')], default='member', max_length=50, verbose_name='Rol')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational.committee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational.employee')),
            ],
            options={
                'verbose_name': 'Membresía en Comité',
                'verbose_name_plural': 'Membresías en Comités',
                'unique_together': {('committee', 'employee', 'start_date')},
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(through='organizational.CommitteeMembership', to='organizational.employee', verbose_name='Miembros'),
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('objective', models.TextField(verbose_name='Objetivo del Puesto')),
                ('education_required', models.CharField(max_length=200, verbose_name='Escolaridad Requerida')),
                ('experience_required', models.CharField(max_length=200, verbose_name='Experiencia Requerida')),
                ('technical_skills', models.JSONField(default=list, verbose_name='Habilidades Técnicas')),
                ('soft_skills', models.JSONField(default=list, verbose_name='Habilidades Blandas')),
                ('owned_processes', models.JSONField(default=list, verbose_name='Procesos que Posee')),
                ('participates_in', models.JSONField(default=list, verbose_name='Procesos en los que Participa')),
                ('performance_indicators', models.JSONField(default=list, verbose_name='Indicadores de Desempeño')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='organizational.position')),
            ],
            options={
                'verbose_name': 'Perfil de Puesto',
                'verbose_name_plural': 'Perfiles de Puesto',
            },
        ),
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('assignment_type', models.CharField(choices=[('permanent', 'Permanente'), ('temporary', 'Temporal'), ('interim', 'Interino')], default='permanent', max_length=20, verbose_name='Tipo de Asignación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organizational.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organizational.position')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'unique_together': {('position', 'employee', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('level', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], default=1, verbose_name='Nivel')),
                ('status', models.CharField(choices=[('certified', 'Certificado'), ('training', 'En Capacitación'), ('needs_training', 'Necesita Capacitación'), ('expired', 'Certificación Vencida')], default='needs_training', max_length=20, verbose_name='Estado')),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Certificación')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='organizational.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizational.skill')),
            ],
            options={
                'verbose_name': 'Competencia del Empleado',
                'verbose_name_plural': 'Competencias de Empleados',
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
