# Generated by Django 5.2.7 on 2025-12-01 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0002_committee_skill_alter_position_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Organigrama')),
                ('department', models.CharField(choices=[('Administrativo', 'Administrativo'), ('Comercial', 'Comercial'), ('Operaciones', 'Operaciones'), ('RRHH', 'Recursos Humanos'), ('Finanzas', 'Finanzas'), ('Mantenimiento', 'Mantenimiento')], max_length=100, verbose_name='Departamento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('chart_file', models.FileField(blank=True, null=True, upload_to='organigramas/', verbose_name='Archivo del Organigrama')),
                ('chart_data', models.JSONField(blank=True, default=dict, verbose_name='Datos del Organigrama')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_external', models.BooleanField(default=False, help_text='Indica si el organigrama fue subido desde un archivo externo', verbose_name='Archivo Externo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Organigrama Departamental',
                'verbose_name_plural': 'Organigramas Departamentales',
                'ordering': ['-updated_at'],
            },
        ),
    ]
