# Generated by Django 5.2.7 on 2025-12-01 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0003_departmentalchart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentalchart',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='departmentalchart',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_charts', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='departmentalchart',
            name='change_justification',
            field=models.TextField(blank=True, help_text='Razón por la cual se realizó este cambio', verbose_name='Justificación del Cambio'),
        ),
        migrations.AddField(
            model_name='departmentalchart',
            name='import_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos de Importación'),
        ),
        migrations.AddField(
            model_name='departmentalchart',
            name='import_source',
            field=models.CharField(choices=[('manual', 'Creación Manual'), ('excel', 'Importación Excel'), ('csv', 'Importación CSV'), ('visio', 'Importación Visio'), ('api', 'API Externa')], default='manual', max_length=50, verbose_name='Origen de Datos'),
        ),
        migrations.AddField(
            model_name='departmentalchart',
            name='is_sandbox',
            field=models.BooleanField(default=False, help_text='Indica si es una simulación/propuesta de reestructura', verbose_name='Modo Simulación'),
        ),
        migrations.AddField(
            model_name='departmentalchart',
            name='parent_chart',
            field=models.ForeignKey(blank=True, help_text='Organigrama del cual se clonó esta simulación', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizational.departmentalchart', verbose_name='Organigrama Base'),
        ),
        migrations.AddField(
            model_name='departmentalchart',
            name='version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='departmentalchart',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('sandbox', 'Simulación'), ('pending_approval', 'Pendiente Aprobación'), ('active', 'Activo'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('request_notes', models.TextField(verbose_name='Notas de Solicitud')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Notas de Aprobación')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='organizational.departmentalchart')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flujo de Aprobación',
                'verbose_name_plural': 'Flujos de Aprobación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('import_type', models.CharField(choices=[('excel', 'Excel/CSV'), ('visio', 'Microsoft Visio'), ('api', 'API Externa'), ('json', 'Archivo JSON')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_success', models.IntegerField(default=0)),
                ('records_errors', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='organizational.departmentalchart')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Importación',
                'verbose_name_plural': 'Registros de Importación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('snapshot_data', models.JSONField(verbose_name='Datos de la Instantánea')),
                ('version_tag', models.CharField(max_length=50, verbose_name='Etiqueta de Versión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='organizational.departmentalchart')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instantánea Organizacional',
                'verbose_name_plural': 'Instantáneas Organizacionales',
                'ordering': ['-created_at'],
            },
        ),
    ]
