# Generated by Django 5.2.7 on 2025-12-02 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0004_departmentalchart_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category_type', models.CharField(choices=[('operational', 'Procesos Operativos'), ('strategic', 'Procesos Estratégicos'), ('support', 'Procesos de Soporte'), ('audit', 'Procesos de Auditoría')], max_length=20, verbose_name='Tipo')),
                ('color', models.CharField(default='#059669', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='fas fa-sitemap', max_length=50, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Categoría de Proceso',
                'verbose_name_plural': 'Categorías de Procesos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlowchartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('hr', 'Recursos Humanos'), ('finance', 'Finanzas'), ('operations', 'Operaciones'), ('quality', 'Calidad'), ('it', 'Tecnología'), ('audit', 'Auditoría')], max_length=20, verbose_name='Categoría')),
                ('template_data', models.JSONField(verbose_name='Datos de la Plantilla')),
                ('difficulty_level', models.CharField(choices=[('simple', 'Simple (1-5 pasos)'), ('medium', 'Medio (6-15 pasos)'), ('complex', 'Complejo (16+ pasos)')], max_length=10, verbose_name='Nivel de Dificultad')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Veces Utilizada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Flujograma',
                'verbose_name_plural': 'Plantillas de Flujogramas',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlowchartProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Proceso')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('responsible_department', models.CharField(max_length=100, verbose_name='Departamento Responsable')),
                ('complexity_level', models.CharField(choices=[('simple', 'Simple (1-5 pasos)'), ('medium', 'Medio (6-15 pasos)'), ('complex', 'Complejo (16+ pasos)')], default='simple', max_length=10, verbose_name='Nivel de Complejidad')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Duración Estimada')),
                ('frequency', models.CharField(blank=True, max_length=50, verbose_name='Frecuencia de Ejecución')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_template', models.BooleanField(default=False, verbose_name='Es Plantilla')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Notas de Aprobación')),
                ('diagram_data', models.JSONField(default=dict, verbose_name='Datos del Diagrama')),
                ('canvas_settings', models.JSONField(default=dict, verbose_name='Configuración del Canvas')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Visualizaciones')),
                ('last_executed', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_flowchart_processes', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_flowchart_processes', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('parent_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizational.flowchartprocess', verbose_name='Proceso Padre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational.processcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Proceso de Flujograma',
                'verbose_name_plural': 'Procesos de Flujogramas',
                'ordering': ['-updated_at'],
            },
        ),
    ]
