# Generated by Django 5.2.7 on 2025-12-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0005_processcategory_flowcharttemplate_flowchartprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcategory',
            name='category_type',
            field=models.CharField(choices=[('operational', 'Procesos Operativos'), ('strategic', 'Procesos Estratégicos'), ('support', 'Procesos de Soporte'), ('audit', 'Procesos de Auditoría'), ('quality', 'Procesos de Calidad'), ('safety', 'Procesos de Seguridad'), ('finance', 'Procesos Financieros'), ('hr', 'Procesos de RRHH'), ('it', 'Procesos de TI'), ('legal', 'Procesos Legales')], max_length=20, verbose_name='Tipo'),
        ),
    ]
