# Generated by Django 5.2.7 on 2025-12-02 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('category_type', models.CharField(choices=[('operational', 'Procedimientos Operativos'), ('administrative', 'Procedimientos Administrativos'), ('quality', 'Procedimientos de Calidad'), ('safety', 'Procedimientos de Seguridad'), ('audit', 'Procedimientos de Auditoría'), ('transport', 'Procedimientos de Transporte'), ('maintenance', 'Procedimientos de Mantenimiento'), ('hr', 'Procedimientos de RRHH'), ('finance', 'Procedimientos Financieros'), ('legal', 'Procedimientos Legales')], max_length=50, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='fas fa-file-alt', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Procedimiento',
                'verbose_name_plural': 'Categorías de Procedimientos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('objective', models.TextField(verbose_name='Objetivo')),
                ('scope', models.TextField(verbose_name='Alcance')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('criticality', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Criticidad')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('on_demand', 'Por Demanda')], max_length=20, verbose_name='Frecuencia')),
                ('responsible_position', models.CharField(max_length=200, verbose_name='Puesto Responsable')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vigencia')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Etiquetas')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración Estimada (minutos)')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_procedures', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.procedurecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('file', models.FileField(upload_to='procedures/attachments/', verbose_name='Archivo')),
                ('file_type', models.CharField(max_length=50, verbose_name='Tipo de Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='procedures.procedure', verbose_name='Procedimiento')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
        migrations.CreateModel(
            name='ProcedureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('template_content', models.JSONField(verbose_name='Contenido de Plantilla')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.procedurecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Plantilla de Procedimiento',
                'verbose_name_plural': 'Plantillas de Procedimientos',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('step_number', models.PositiveIntegerField(verbose_name='Número de Paso')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('responsible', models.CharField(max_length=200, verbose_name='Responsable')),
                ('estimated_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo Estimado (minutos)')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Paso Crítico')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procedures.procedure', verbose_name='Procedimiento')),
            ],
            options={
                'verbose_name': 'Paso de Procedimiento',
                'verbose_name_plural': 'Pasos de Procedimientos',
                'ordering': ['procedure', 'step_number'],
                'unique_together': {('procedure', 'step_number')},
            },
        ),
    ]
