# Generated by Django 5.2.7 on 2025-12-01 10:18

from django.db import migrations

def update_manuales_category(apps, schema_editor):
    Category = apps.get_model('knowledge_base', 'Category')
    
    # Verificar si ya existe "manuales"
    manuales_exists = Category.objects.filter(slug='manuales').exists()
    
    if manuales_exists:
        return  # Ya existe, no hacer nada
    
    # Buscar la categoría "Manuales Operativos" y cambiarla a "Manuales"
    try:
        manuales_operativos = Category.objects.get(slug='manuales-operativos')
        manuales_operativos.name = 'Manuales'
        manuales_operativos.slug = 'manuales'
        manuales_operativos.description = 'Documentacion completa de procesos, procedimientos y manuales operativos de ICASA'
        manuales_operativos.icon = 'fas fa-book'
        manuales_operativos.color = '#8b5cf6'  # Purple
        manuales_operativos.save()
    except Category.DoesNotExist:
        # Si no existe, crear la categoría Manuales
        Category.objects.create(
            name='Manuales',
            slug='manuales',
            description='Documentacion completa de procesos, procedimientos y manuales operativos de ICASA',
            icon='fas fa-book',
            color='#8b5cf6',
            is_active=True
        )

def reverse_update_manuales_category(apps, schema_editor):
    Category = apps.get_model('knowledge_base', 'Category')
    
    try:
        manuales = Category.objects.get(slug='manuales')
        manuales.name = 'Manuales Operativos'
        manuales.slug = 'manuales-operativos'
        manuales.save()
    except Category.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_alter_document_content'),
    ]

    operations = [
        migrations.RunPython(
            update_manuales_category,
            reverse_update_manuales_category
        ),
    ]
