# Generated by Django 5.2.7 on 2025-12-01 10:20

from django.db import migrations

def create_manual_subcategories(apps, schema_editor):
    Category = apps.get_model('knowledge_base', 'Category')
    
    # Buscar la categoría padre "Manuales"
    try:
        manuales_parent = Category.objects.get(slug='manuales')
    except Category.DoesNotExist:
        return  # No existe la categoría padre
    
    # Subcategorías a crear
    subcategories = [
        {
            'name': 'Operativos',
            'slug': 'operativos',
            'description': 'Manuales de procesos core del negocio de seguros',
            'icon': 'fas fa-cogs',
            'color': '#10b981'
        },
        {
            'name': 'Gestion y Control',
            'slug': 'gestion-control',
            'description': 'Manuales de calidad, riesgos y cumplimiento',
            'icon': 'fas fa-shield-alt',
            'color': '#f59e0b'
        },
        {
            'name': 'Recursos Humanos',
            'slug': 'recursos-humanos',
            'description': 'Manuales de gestion del talento humano',
            'icon': 'fas fa-users',
            'color': '#3b82f6'
        },
        {
            'name': 'Tecnologia',
            'slug': 'tecnologia',
            'description': 'Manuales de sistemas y seguridad informatica',
            'icon': 'fas fa-laptop-code',
            'color': '#8b5cf6'
        }
    ]
    
    # Crear subcategorías si no existen
    for subcat_data in subcategories:
        if not Category.objects.filter(slug=subcat_data['slug'], parent=manuales_parent).exists():
            Category.objects.create(
                name=subcat_data['name'],
                slug=subcat_data['slug'],
                description=subcat_data['description'],
                icon=subcat_data['icon'],
                color=subcat_data['color'],
                parent=manuales_parent,
                is_active=True
            )

def reverse_create_manual_subcategories(apps, schema_editor):
    Category = apps.get_model('knowledge_base', 'Category')
    
    # Eliminar subcategorías creadas
    subcategory_slugs = ['operativos', 'gestion-control', 'recursos-humanos', 'tecnologia']
    
    try:
        manuales_parent = Category.objects.get(slug='manuales')
        Category.objects.filter(slug__in=subcategory_slugs, parent=manuales_parent).delete()
    except Category.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_update_manuales_category'),
    ]

    operations = [
        migrations.RunPython(
            create_manual_subcategories,
            reverse_create_manual_subcategories
        ),
    ]
