# Generated by Django 5.2.7 on 2025-11-25 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('notification_type', models.CharField(choices=[('document_created', 'Documento Creado'), ('document_approved', 'Documento Aprobado'), ('document_rejected', 'Documento Rechazado'), ('document_review', 'Documento en Revisión'), ('user_mentioned', 'Usuario Mencionado'), ('system_update', 'Actualización del Sistema')], max_length=50, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('action_url', models.URLField(blank=True, verbose_name='URL de acción')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_document_created', models.BooleanField(default=True, verbose_name='Email: Documento creado')),
                ('email_document_approved', models.BooleanField(default=True, verbose_name='Email: Documento aprobado')),
                ('email_document_rejected', models.BooleanField(default=True, verbose_name='Email: Documento rechazado')),
                ('email_document_review', models.BooleanField(default=True, verbose_name='Email: Documento en revisión')),
                ('web_document_created', models.BooleanField(default=True, verbose_name='Web: Documento creado')),
                ('web_document_approved', models.BooleanField(default=True, verbose_name='Web: Documento aprobado')),
                ('web_document_rejected', models.BooleanField(default=True, verbose_name='Web: Documento rechazado')),
                ('web_document_review', models.BooleanField(default=True, verbose_name='Web: Documento en revisión')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
    ]
