# Generated by Django 5.2.7 on 2025-11-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de acción'),
        ),
    ]
